/***
 * JSDoc type definitions for the Steam Web API's ISteamPublishedItemSearch.
 * @see https://partner.steamgames.com/doc/webapi/ISteamPublishedItemSearch
 */

// ---- Helper Interfaces ----

/*** Represents a tag on a published item.
 * @description A tag used for categorization.
 */
export interface PublishedItemTag {
	/**
	 * @description The raw tag string.
	 */
	tag: string;
}

/*** Represents voting information for a published item.
 * @description Aggregated vote counts and score for an item.
 */
export interface PublishedItemVoteInfo {
	/**
	 * @minimum 0
	 * @description The number of 'up' votes.
	 */
	votes_for: number;
	/**
	 * @minimum 0
	 * @description The number of 'down' votes.
	 */
	votes_against: number;
	/**
	 * @description The calculated score, typically between 0 and 1.
	 */
	score: number;
}

/*** Represents the details of a published item from a search result.
 * @description A comprehensive object containing metadata for a single published item.
 */
export interface PublishedItemSearchResultDetail {
	/**
	 * @pattern "^[0-9]+$"
	 * @description The unique 64-bit ID of the published file.
	 */
	publishedfileid: string;
	/**
	 * @pattern "^[0-9]{17}$"
	 * @description The 64-bit SteamID of the user who created the item.
	 */
	creator: string;
	/**
	 * @minimum 1
	 * @description The AppID the item is for.
	 */
	item_appid: number;
	/**
	 * @description The title of the item.
	 */
	title: string;
	/**
	 * @description The description of the item.
	 */
	description: string;
	/**
	 * @format url
	 * @description The URL to the item's Workshop page.
	 */
	url: string;
	/**
	 * @format url
	 * @description The URL of the item's preview image.
	 */
	preview_url: string;
	/**
	 * @format unix-timestamp
	 * @description The time the item was created.
	 */
	time_created: number;
	/**
	 * @format unix-timestamp
	 * @description The time the item was last updated.
	 */
	time_updated: number;
	/**
	 * @minimum 0
	 * @description The number of current subscribers.
	 */
	subscriptions: number;
	/**
	 * @minimum 0
	 * @description The number of users who have favorited this item.
	 */
	favorited: number;
	/**
	 * @minimum 0
	 * @description The number of times the item has been viewed.
	 */
	views: number;
	/**
	 * @minimum 0
	 * @description The number of lifetime subscribers.
	 */
	lifetime_subscriptions: number;
	/**
	 * @minimum 0
	 * @description The number of lifetime favorites.
	 */
	lifetime_favorited: number;
	/**
	 * @description True if the item is banned.
	 */
	banned: boolean;
	/**
	 * @description The reason the item was banned, if applicable.
	 */
	ban_reason: string;
	/**
	 * @description Developer-specific metadata string.
	 */
	metadata: string;
	/**
	 * @description An array of tags associated with the item.
	 */
	tags: PublishedItemTag[];
	/**
	 * @description Voting information for the item.
	 */
	voteinfo: PublishedItemVoteInfo;
}

/*** Represents a group of tags for advanced filtering.
 * @description Used to specify that an item must have at least one tag from each group.
 */
export interface RequiredTagGroup {
	/**
	 * @description An array of tag strings. An item must match at least one tag in this array.
	 */
	tags: string[];
}

/*** The common response structure for search and pagination requests.
 * @description Contains the search results and pagination information.
 */
export interface PublishedItemSearchResponse {
	response: {
		/**
		 * @minimum 0
		 * @description The total number of results matching the search criteria.
		 */
		totalresults: number;
		/**
		 * @minimum 0
		 * @description The starting index for the next page of results.
		 */
		nextstartindex: number;
		/**
		 * @description An array of published item details.
		 */
		publisheditemdetails: PublishedItemSearchResultDetail[];
	};
}

// ---- API Endpoint Interfaces ----

/*** The base parameters for all `RankedBy...` search methods.
 * @description Common parameters for initiating a ranked search.
 * @remarks A `sessionid` should be generated by the client for the initial search call and then reused for subsequent `ResultSet_GetNextPage` calls.
 */
export interface BaseRankedByRequest {
	key: string;
	/**
	 * @pattern "^[0-9]{17}$"
	 * @description The 64-bit SteamID of the user performing the search.
	 */
	steamid: string;
	/**
	 * @minimum 1
	 * @description The AppID for which the items are being searched.
	 */
	appid: number;
	/**
	 * @description A client-generated session ID to be used for paging.
	 */
	sessionid: string;
	/**
	 * @minimum 1
	 * @description The number of results to return.
	 */
	count: number;
	/**
	 * @minimum 0
	 * @description The starting index for the search results.
	 */
	startindex: number;
	/**
	 * @description An array of required tags.
	 */
	tag: string[];
	/**
	 * @description An array of required user-generated tags.
	 */
	user_tag: string[];
	/**
	 * @description A JSON-encoded string representing an array of `RequiredTagGroup` objects for advanced filtering.
	 */
	required_tag_groups?: string;
	/**
	 * @description The language for localization of text.
	 */
	language?: string;
	/**
	 * @description Text to search for in the item's title and description.
	 */
	search_text?: string;
	/**
	 * @description If true, returns item details.
	 */
	return_details?: boolean;
	/**
	 * @description If true, returns item tags.
	 */
	return_tags?: boolean;
	/**
	 * @description If true, returns developer metadata.
	 */
	return_metadata?: boolean;
}

/*** Parameters for the ISteamPublishedItemSearch/RankedByVote/v1 endpoint.
 * @see https://partner.steamgames.com/doc/webapi/ISteamPublishedItemSearch#RankedByVote
 * @description Parameters for searching items ranked by vote score.
 */
export type RankedByVoteRequest = BaseRankedByRequest;

/*** Parameters for the ISteamPublishedItemSearch/RankedByPublicationOrder/v1 endpoint.
 * @see https://partner.steamgames.com/doc/webapi/ISteamPublishedItemSearch#RankedByPublicationOrder
 * @description Parameters for searching items ranked by publication date.
 */
export type RankedByPublicationOrderRequest = BaseRankedByRequest;

/*** Parameters for the ISteamPublishedItemSearch/RankedByAcceptanceDate/v1 endpoint.
 * @see https://partner.steamgames.com/doc/webapi/ISteamPublishedItemSearch#RankedByAcceptanceDate
 * @description Parameters for searching items ranked by acceptance date (for curated workshops).
 */
export type RankedByAcceptanceDateRequest = BaseRankedByRequest;

/*** Parameters for the ISteamPublishedItemSearch/RankedByVoteAndReported/v1 endpoint.
 * @see https://partner.steamgames.com/doc/webapi/ISteamPublishedItemSearch#RankedByVoteAndReported
 * @description Parameters for searching items ranked by vote and reported status.
 */
export type RankedByVoteAndReportedRequest = BaseRankedByRequest;

/*** Parameters for the ISteamPublishedItemSearch/RankedByTrend/v1 endpoint.
 * @see https://partner.steamgames.com/doc/webapi/ISteamPublishedItemSearch#RankedByTrend
 * @description Parameters for searching items ranked by recent trend.
 */
export interface RankedByTrendRequest extends BaseRankedByRequest {
	/**
	 * @minimum 1
	 * @description The number of past days to consider for the trend calculation.
	 */
	days: number;
}

/*** Parameters for the ISteamPublishedItemSearch/ResultSet_GetNextPage/v1 endpoint.
 * @see https://partner.steamgames.com/doc/webapi/ISteamPublishedItemSearch#ResultSet_GetNextPage
 * @description Parameters for retrieving the next page of results from a search session.
 */
export interface ResultSetGetNextPageRequest {
	key: string;
	/**
	 * @pattern "^[0-9]{17}$"
	 * @description The 64-bit SteamID of the user who initiated the search.
	 */
	steamid: string;
	/**
	 * @minimum 1
	 * @description The AppID of the search.
	 */
	appid: number;
	/**
	 * @description The session ID from the initial search call.
	 */
	sessionid: string;
	/**
	 * @minimum 0
	 * @description The starting index for the next page, usually from the previous response's `nextstartindex`.
	 */
	startindex: number;
	/**
	 * @minimum 1
	 * @description The number of results to return for this page.
	 */
	count: number;
	/**
	 * @description If true, returns item details.
	 */
	return_details?: boolean;
	/**
	 * @description If true, returns item tags.
	 */
	return_tags?: boolean;
	/**
	 * @description If true, returns developer metadata.
	 */
	return_metadata?: boolean;
}

// All search and pagination methods return the same response structure.
export type RankedByVoteResponse = PublishedItemSearchResponse;
export type RankedByPublicationOrderResponse = PublishedItemSearchResponse;
export type RankedByAcceptanceDateResponse = PublishedItemSearchResponse;
export type RankedByTrendResponse = PublishedItemSearchResponse;
export type RankedByVoteAndReportedResponse = PublishedItemSearchResponse;
export type ResultSetGetNextPageResponse = PublishedItemSearchResponse;
